version: '3.9'

services:
  postgres:
    image: postgres
    container_name: ${APP_NAME}-container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${APP_NAME}
    ports:
      - '5433:5432'
    volumes:
      - notus-data:/var/lib/postgresql/data

volumes:
  notus-data:
